In [1]:
import numpy as np

In [2]:
np.random.seed(0)
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))

In [3]:
x1

array([5, 0, 3, 3, 7, 9])

In [4]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [5]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

# Array Indexing: Accessing Single Elements

In [6]:
x1[0]

5

In [7]:
x1[4]

7

In [8]:
x1[-1]

9

In [9]:
x1[-2]

7

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
x2[2,0]

1

In [12]:
x2[2,-1]

7

In [13]:
#modify values using any of the above index notation

In [14]:
x2[0,0]=11

In [15]:
x2

array([[11,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [16]:
x1

array([5, 0, 3, 3, 7, 9])

In [17]:
x1[0]=3.14 # this will be truncated!

In [18]:
x1

array([3, 0, 3, 3, 7, 9])

# Array Slicing: Accessing Subarrays

# x[start:stop:step]

# One Dimesional SubArrays

In [19]:
x=np.arange(10)

In [20]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[:5]

array([0, 1, 2, 3, 4])

In [22]:
x[4:7]

array([4, 5, 6])

In [23]:
x[::2]

array([0, 2, 4, 6, 8])

In [24]:
x[1::2]

array([1, 3, 5, 7, 9])

In [25]:
#reverse an array
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
x[5::-2]

array([5, 3, 1])

# MultiDimensional SubArrays

In [27]:
x2

array([[11,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [28]:
x2[:2,:3]

array([[11,  5,  2],
       [ 7,  6,  8]])

In [29]:
x2[:3,::2]

array([[11,  2],
       [ 7,  8],
       [ 1,  7]])

In [30]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 11]])

# Subarrays as no-copy views

In [31]:
#One important—and extremely useful—thing to know about array slices is that they
#return views rather than copies of the array data. This is one area in which NumPy
#array slicing differs from Python list slicing: in lists, slices will be copies.

In [32]:
#Example

In [33]:
x2=np.random.randint(0,10,size=(4,4))

In [34]:
x2

array([[4, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1],
       [5, 9, 3, 0]])

In [35]:
#slicing here will create just a view of the original data not copy of it and any changes will be reflected in 
#the original array itself.

In [36]:
sub_x2=x2[:2,:2]

In [38]:
sub_x2

array([[4, 3],
       [8, 4]])

In [39]:
sub_x2[0,0]=99

In [40]:
sub_x2

array([[99,  3],
       [ 8,  4]])

In [41]:
x2

array([[99,  3,  4,  4],
       [ 8,  4,  3,  7],
       [ 5,  5,  0,  1],
       [ 5,  9,  3,  0]])

# Creating copies of arrays

In [42]:
x2=np.random.randint(0,10,(4,4))

In [43]:
x2

array([[5, 0, 1, 2],
       [4, 2, 0, 3],
       [2, 0, 7, 5],
       [9, 0, 2, 7]])

In [44]:
sub_x2_copy=x2[:2,:2].copy()

In [46]:
sub_x2_copy

array([[5, 0],
       [4, 2]])

In [47]:
sub_x2_copy[0,0]=101

In [50]:
sub_x2_copy #here copy is created not a view

array([[101,   0],
       [  4,   2]])

In [51]:
x2

array([[5, 0, 1, 2],
       [4, 2, 0, 3],
       [2, 0, 7, 5],
       [9, 0, 2, 7]])

# Reshaping of Arrays

In [54]:
x=np.arange(1,10)

In [55]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
#now reshaping x into (3,3)

In [57]:
x=x.reshape((3,3))

In [58]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
#making row vector using reshape

In [60]:
x=np.array([1,2,3])

In [61]:
x

array([1, 2, 3])

In [62]:
x=x.reshape((1,3))

In [63]:
x

array([[1, 2, 3]])

In [64]:
#making row vector using newaxis within slicing of array

In [66]:
x=np.array([1,2,3])

In [67]:
x=x[np.newaxis,:]

In [68]:
x

array([[1, 2, 3]])

In [69]:
#column vector using reshape

In [70]:
x=np.array([1,2,3])

In [71]:
x

array([1, 2, 3])

In [72]:
x=x.reshape((3,1))

In [73]:
x

array([[1],
       [2],
       [3]])

In [74]:
#column vector using newaxis

In [75]:
x=np.array([1,2,3])

In [76]:
x

array([1, 2, 3])

In [77]:
x=x[:,np.newaxis]

In [78]:
x

array([[1],
       [2],
       [3]])

# Thank You