# Concatenation of Arrays

In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.array([9,10,11,12])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
y

array([5, 6, 7, 8])

In [5]:
z

array([ 9, 10, 11, 12])

In [6]:
a=np.concatenate([x,y,z]) #axis=0 (by default)

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
grid1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
grid2=np.array([[10,11,12],[13,14,15],[16,17,18]])

In [10]:
grid1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
grid2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [12]:
#two dimensional concatenation

In [13]:
a=np.concatenate([grid1,grid2]) #axis=0 (default)

In [14]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [15]:
a=np.concatenate([grid1,grid2],axis=1) #axis=1

In [16]:
a

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [17]:
#For working with arrays of mixed dimensions, it can be clearer to use the np.vstack
#(vertical stack) and np.hstack (horizontal stack) functions

In [18]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],[6, 5, 4]])

In [19]:
x

array([1, 2, 3])

In [20]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [21]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [22]:
y = np.array([[99],[99]])

In [23]:
y

array([[99],
       [99]])

In [24]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [25]:
np.hstack((grid,y))

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [26]:
#Similarly, np.dstack will stack arrays along the third axis.

# Splitting of arrays

In [29]:
x=np.arange(0,16)

In [30]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
np.split(x,[4,6])

[array([0, 1, 2, 3]),
 array([4, 5]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]

In [32]:
x=np.arange(0,16).reshape((4,4))

In [33]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
np.vsplit(x,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [35]:
np.hsplit(x,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# Exploring NumPy’s UFuncs
Ufuncs exist in two flavors: unary ufuncs, which operate on a single input, and binary
ufuncs, which operate on two inputs. We’ll see examples of both these types of func‐
tions here.

# Array arithmetic

In [36]:
x=np.arange(0,5)

In [37]:
x

array([0, 1, 2, 3, 4])

In [38]:
x+2

array([2, 3, 4, 5, 6])

In [39]:
x-2

array([-2, -1,  0,  1,  2])

In [40]:
x*2

array([0, 2, 4, 6, 8])

In [41]:
x/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [42]:
x//2

array([0, 0, 1, 1, 2])

In [43]:
-x

array([ 0, -1, -2, -3, -4])

In [44]:
x**2

array([ 0,  1,  4,  9, 16])

In [45]:
x%2

array([0, 1, 0, 1, 0])

In [46]:
-(3*x+5)**2

array([ -25,  -64, -121, -196, -289])

# All of these arithmetic operations are simply convenient wrappers around specific
functions built into NumPy; for example, the + operator is a wrapper for the add
function:

In [47]:
np.add(x,2)

array([2, 3, 4, 5, 6])

In [48]:
#+ np.add Addition (e.g., 1 + 1 = 2 )
#- np.subtract Subtraction (e.g., 3 - 2 = 1 )
#- np.negative Unary negation (e.g., -2 )
#* np.multiply Multiplication (e.g., 2 * 3 = 6 )
#/ np.divide Division (e.g., 3 / 2 = 1.5 )
#// np.floor_divide Floor division (e.g., 3 // 2 = 1 )
#** np.power Exponentiation (e.g., 2 ** 3 = 8 )
#% np.mod Modulus/remainder (e.g., 9 % 4 = 1 )

# Absolute value

In [49]:
x=np.arange(-3,3)

In [50]:
x

array([-3, -2, -1,  0,  1,  2])

In [51]:
abs(x)

array([3, 2, 1, 0, 1, 2])

In [52]:
np.absolute(x)

array([3, 2, 1, 0, 1, 2])

In [53]:
np.abs(x)

array([3, 2, 1, 0, 1, 2])

In [54]:
#handling complex numbers

In [55]:
x=np.array([2-3j,3-4j,6+7j,4+8j])

In [56]:
x

array([2.-3.j, 3.-4.j, 6.+7.j, 4.+8.j])

In [57]:
np.abs(x)

array([3.60555128, 5.        , 9.21954446, 8.94427191])

# Trigonometric Functions

In [58]:
angles=np.linspace(0,np.pi,3)

In [59]:
angles

array([0.        , 1.57079633, 3.14159265])

In [60]:
np.sin(angles)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [61]:
np.cos(angles)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [62]:
np.tan(angles)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [63]:
#inverse trigonometric functions are also available

In [66]:
x=[-1,0,1]

In [67]:
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [69]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [70]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

# Exponents and logarithms

In [71]:
x=[1,2,3]

In [72]:
print("x : ",x)
print("e^x : ",np.exp(x))
print("2^x : ",np.exp2(x))
print("3^x : ",np.power(3,x))

x :  [1, 2, 3]
e^x :  [ 2.71828183  7.3890561  20.08553692]
2^x :  [2. 4. 8.]
3^x :  [ 3  9 27]


In [73]:
print("ln x : ",np.log(x))
print("log2x : ",np.log2(x))
print("log10x : ",np.log10(x))

ln x :  [0.         0.69314718 1.09861229]
log2x :  [0.        1.        1.5849625]
log10x :  [0.         0.30103    0.47712125]


In [74]:
x = [0, 0.001, 0.01, 0.1]

In [76]:
print("exp(x) - 1 =",np.expm1(1))
print("log(1+x) =",np.log1p(1))

exp(x) - 1 = 1.718281828459045
log(1+x) = 0.6931471805599453


In [77]:
#When x is very small, these functions give more precise values than if the raw np.log
#or np.exp were used.

# Thank You