In [1]:
import numpy as np

# Working with Boolean Arrays

In [3]:
x=np.array([[5 ,0 ,3 ,3],
[7, 9, 3 ,5],
[2, 4, 7, 6]])

In [6]:
#counting non zero entries in a boolean array

In [7]:
x<6 #boolean array

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [8]:
np.count_nonzero(x<6)

8

In [9]:
#another way of doing the same

In [10]:
np.sum(x<6)

8

In [11]:
#The benefit of sum() is that like with other NumPy aggregation functions, this summation can be done along rows or columns as well

In [13]:
np.sum(x<6,axis=0)

array([2, 2, 2, 2])

In [14]:
np.sum(x<6,axis=1)

array([4, 2, 2])

In [15]:
#determine if any value is true or not
np.any(x<6)

True

In [16]:
#determine if all values are true or not
np.all(x<6)

False

In [17]:
np.all(x<6,axis=1)

array([ True, False, False])

# Boolean operators

In [18]:
x=np.array([1,0,1,0])
y=np.array([0,1,1,0])

In [19]:
x&y

array([0, 0, 1, 0])

In [20]:
x|y

array([1, 1, 1, 0])

In [22]:
x=np.array([True,False,True,True])

In [23]:
~x

array([False,  True, False, False])

In [24]:
#xor

In [25]:
x^y

array([1, 1, 0, 1])

# Boolean Arrays as Masks

In [26]:
#using boolean arrays as masks

In [27]:
x=np.random.randint(0,10,size=(3,4))

In [28]:
x

array([[4, 0, 1, 4],
       [4, 6, 8, 1],
       [6, 9, 4, 7]])

In [29]:
x<5

array([[ True,  True,  True,  True],
       [ True, False, False,  True],
       [False, False,  True, False]])

In [31]:
#to select these values from the array, we can simply index on this Boolean array;
#this is known as a masking operation

x[x<5]

array([4, 0, 1, 4, 4, 1, 4])

# Fancy Indexing

In [32]:
#Fancy indexing is like the simple indexing but we pass
#arrays of indices in place of single scalars. This allows us to very quickly access and
#modify complicated subsets of an array’s values.

In [33]:
x=np.random.randint(100,size=10)

In [34]:
x

array([30, 29, 22, 58, 22, 97, 74, 79, 57, 64])

In [35]:
# we want to access the fourth,fifth and seventh element using fancy indexing

In [36]:
ind=[3,4,6]

In [37]:
x[ind]

array([58, 22, 74])

In [38]:
#With fancy indexing, the shape of the result reflects the shape of the index arrays
#rather than the shape of the array being indexed

In [40]:
ind=np.array([[3,4],[6,7]])

In [41]:
ind

array([[3, 4],
       [6, 7]])

In [42]:
x[ind]

array([[58, 22],
       [74, 79]])

In [43]:
#Fancy indexing also works in multiple dimensions.

In [44]:
X = np.arange(12).reshape((3, 4))

In [45]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
row=np.array([0,1,2])
col=np.array([2,1,3])  

In [49]:
X[row,col]  #[(0,2),(1,1),(2,3)]

array([ 2,  5, 11])

In [50]:
#The pairing of indices in fancy indexing follows all the broadcasting rules

In [52]:
X[row[:,np.newaxis],col]  

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

# Combined Indexing

In [53]:
#For even more powerful operations, fancy indexing can be combined with the other
#indexing schemes

In [54]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
#We can combine fancy and simple indices:
X[1,[1,3,0]]

array([5, 7, 4])

In [57]:
#We can also combine fancy indexing with slicing:

In [59]:
X[1:,[1,3,2]]

array([[ 5,  7,  6],
       [ 9, 11, 10]])

In [60]:
#we can combine fancy indexing with masking

In [61]:
mask=np.array([1,0,1,0],dtype=bool)

In [62]:
mask

array([ True, False,  True, False])

In [63]:
row

array([0, 1, 2])

In [64]:
X[row[:,np.newaxis],mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

# Sorting Arrays

In [65]:
x = np.array([2, 1, 4, 3, 5])

In [66]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [67]:
x

array([2, 1, 4, 3, 5])

In [68]:
x.sort()

In [69]:
x

array([1, 2, 3, 4, 5])

In [70]:
#A related function is argsort , which instead returns the indices of the sorted elements

In [71]:
np.argsort(x)

array([0, 1, 2, 3, 4])

In [72]:
x[np.argsort(x)]

array([1, 2, 3, 4, 5])

# Sorting along rows or columns

In [73]:
x=np.random.randint(0,10,size=(4,6))

In [74]:
x

array([[7, 4, 9, 3, 4, 0],
       [9, 0, 3, 8, 2, 4],
       [1, 8, 2, 7, 2, 9],
       [3, 3, 5, 9, 0, 8]])

In [75]:
np.sort(x,axis=0)

array([[1, 0, 2, 3, 0, 0],
       [3, 3, 3, 7, 2, 4],
       [7, 4, 5, 8, 2, 8],
       [9, 8, 9, 9, 4, 9]])

In [76]:
np.sort(x,axis=1)

array([[0, 3, 4, 4, 7, 9],
       [0, 2, 3, 4, 8, 9],
       [1, 2, 2, 7, 8, 9],
       [0, 3, 3, 5, 8, 9]])

# Partial Sorts: Partitioning

In [79]:
#np.partition takes an array and a number K; the result is a new array with the small‐
#est K values to the left of the partition, and the remaining values to the right, in arbi‐
#trary order
x = np.array([7, 2, 3, 1, 6, 5, 4])

In [80]:
np.partition(x,3)

array([2, 1, 3, 4, 6, 5, 7])

In [81]:
#we can partition along an arbitrary axis of a multidimensional array

In [85]:
X=np.random.randint(100,size=(4,6))
X

array([[23, 66, 52, 66, 76, 77],
       [63, 71, 79, 38, 10, 78],
       [19, 29, 48, 18, 53, 85],
       [77, 36, 63, 10, 38, 65]])

In [86]:
np.partition(X,2,axis=0)

array([[19, 29, 48, 10, 10, 65],
       [23, 36, 52, 18, 38, 77],
       [63, 66, 63, 38, 53, 78],
       [77, 71, 79, 66, 76, 85]])

In [95]:
#there is a np.argpartition that computes indices of the partition.

# Structured Data: NumPy’s Structured Arrays

In [96]:
#Imagine that we have several categories of data on a number of people (say, name,
#age, and weight), and we’d like to store these values for use in a Python program. It
#would be possible to store these in three separate arrays

In [97]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [98]:
#But this is a bit clumsy. There’s nothing here that tells us that the three arrays are
#related; it would be more natural if we could use a single structure to store all of this
#data. NumPy can handle this through structured arrays, which are arrays with com‐
#pound data types.

In [99]:
data=np.zeros(4,dtype={'names':('name','age','weight'),'formats':('U10','i4','f8')})

In [100]:
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [101]:
#Here 'U10' translates to “Unicode string of maximum length 10,” 'i4' translates to
#“4-byte (i.e., 32 bit) integer,” and 'f8' translates to “8-byte (i.e., 64 bit) float.”

In [102]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [103]:
data['name']=name
data['age']=age
data['weight']=weight

In [104]:
data

array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. ),
       ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

# Creating Structured Arrays

In [105]:
#For clarity, numerical types can be specified with Python types or NumPy dtype s
#instead:

In [106]:
np.dtype({'names':('name', 'age', 'weight'),
'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [107]:
#A compound type can also be specified as a list of tuples:

In [108]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

# Thank You