In [1]:
import numpy as np

# Creating Numpy Arrays From Python List

In [3]:
#integer array
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [4]:
#Numpy will upcast things(If Possible) if datatypes in array are not same
#here integers are upcast to floating point
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
#If we want to explicitly set the data type of the resulting array, we can use the dtype
#keyword

np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
#Finally, unlike Python lists, NumPy arrays can explicitly be multidimensional; here’s
#one way of initializing a multidimensional array using a list of lists

In [7]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
#The inner lists are treated as rows of the resulting two-dimensional array.

# Creating Arrays from Scratch

In [10]:
# Create a length-10 integer array filled with zeros

In [14]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# Create a 3x5 floating-point array filled with 1s

In [16]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# Create a 3x5 array filled with 3.14
np.full(shape=(3,5),fill_value=3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [18]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
#Create a 3x3 array of uniformly distributed
# random values between 0 and 1

np.random.random((3,3))

array([[0.36697399, 0.76147921, 0.46799404],
       [0.05049429, 0.08481375, 0.9496487 ],
       [0.86905386, 0.7270096 , 0.67307676]])

In [23]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 0.07185835, -0.46514412, -0.15834677],
       [ 0.39514144,  0.35826387, -0.06240373],
       [-1.13996422, -1.0986638 , -1.88787896]])

In [24]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,size=(3,3))

array([[2, 2, 9],
       [4, 6, 3],
       [6, 7, 8]])

In [25]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

# NumPy Standard Data Types

In [27]:
#Note that when constructing
#an array, you can specify them using a string:
np.zeros(10,dtype="int16")
# or using the associated Numpy Object
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

# Data type  Description

In [28]:
# bool_ Boolean (True or False) stored as a byte
# int_ Default integer type (same as C long ; normally either int64 or int32 )
#intc Identical to C int (normally int32 or int64 )
#intp Integer used for indexing (same as C ssize_t ; normally either int32 or int64 )
#int8 Byte (–128 to 127)
#int16 Integer (–32768 to 32767)
#int32 Integer (–2147483648 to 2147483647)
#int64 Integer (–9223372036854775808 to 9223372036854775807)
#uint8 Unsigned integer (0 to 255)
#uint16 Unsigned integer (0 to 65535)
#uint32 Unsigned integer (0 to 4294967295)
#uint64 Unsigned integer (0 to 18446744073709551615)
#float_ Shorthand for float64
#float16 Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa
#float32 Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa
#float64 Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa
#complex_ Shorthand for complex128
#complex64 Complex number, represented by two 32-bit floats
#complex128 Complex number, represented by two 64-bit floats

# NumPy Array Attributes

In [29]:
np.random.seed(0) #seed for reproducibility
x1=np.random.randint(10,size=6) # 1D array
x2=np.random.randint(10,size=(3,4)) #2D array
x3=np.random.randint(10,size=(3,4,5))# 3D array

In [30]:
x1

array([5, 0, 3, 3, 7, 9])

In [31]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [32]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [34]:
#Each array has attributes ndim (the number of dimensions), shape (the size of each
#dimension), and size (the total size of the array)

In [35]:
print("x3 ndim : ",x3.ndim)
print("x3 shape : ",x3.shape)
print("x3 size : ",x3.size)

x3 ndim :  3
x3 shape :  (3, 4, 5)
x3 size :  60


In [36]:
print("x3 dtype : ",x3.dtype)

x3 dtype :  int64


In [37]:
print("x3 itemsize : ",x3.itemsize ," bytes")
print("x3 nbytes : ",x3.nbytes , " bytes")

x3 itemsize :  8  bytes
x3 nbytes :  480  bytes


# Thank You